### ISSUE TITLE
[BUG] should not hard code setuptools version line in pyproject.toml file. 

### ISSUE THREAD

**Issue by haiwu** [container-registry/harbor-api-client#5]
@alexandre-k : Could you please remove this line here? 21.0.0 is super old (2016). 
https://github.com/container-registry/harbor-api-client/blame/master/pyproject.toml#L22

It is causing this python module installation dependency conflict.

**Comment by alexandre-k** [comment]
Thank you for your report.
I removed the hardcoded _setuptools_ dependency and updated the harbor-api-client package to 2.7.5. If you update the version it should fix your conflict.
Waiting for your feedback to confirm it works on your side.

**Comment by haiwu** [comment]
Perfect! This is now working. Thanks!
